apiVersion: v1
kind: Service
metadata:
  name: items
spec:
  selector:
    app: items
  ports:
    - port: 8080
      targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
spec:
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
      annotations:
        v: "0"
    spec:
      containers:
        - name: items
          env:
            - name: MongoPass
              value: cLJBxAPrnY
            - name: MongoHost
              value: my-release-mongodb.mongo.svc.cluster.local
          image: tiegris/apples-items:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8079
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: items-pvc
spec:
  resources:
    requests:
      storage: 50M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
