apiVersion: v1
kind: Pod
metadata:
  name: my-test-2
  labels:
    app: my-test-2
spec:
  containers:
  - name: myapp
    image: "there-is-no-way-an-image-exists-with-this-tag-on-docker.io"
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8443
---
apiVersion: v1
kind: Pod
metadata:
  name: my-test
  labels:
    app: my-test
spec:
  containers:
  - name: myapp
    image: alpine
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: mz-test
spec:
  selector:
    app: mz-test # deliberate typo 
  ports:
  - port: 8443
    targetPort: 8443
