apiVersion: v1
kind: Pod
metadata:
  name: demo-backoff
  labels:
    app: demo-backoff
spec:
  containers:
  - name: myapp
    image: "there-is-no-way-an-image-exists-with-this-tag-on-docker.io"
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8443