apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
spec:
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting
    spec:
      containers:
        - image: alpine
          command: ["sleep", "infinity"]

