apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-test
spec:
  selector:
    matchLabels:
      app: policy-test
  template:
    metadata:
      labels:
        app: policy-test
    spec:
      containers:
        - image: alpine
          name: policy-test
          command: ["sleep", "infinity"]
