apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "konstrainr-core.fullname" . }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["deployments", "services", "secrets"]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "konstrainr-core.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "konstrainr-core.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "konstrainr-core.fullname" . }}
  apiGroup: rbac.authorization.k8s.io