apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "konstrainr-core.fullname" . }}
  labels:
    {{- include "konstrainr-core.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "konstrainr-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "konstrainr-core.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ include "konstrainr-core.fullname" . }}-storage
        persistentVolumeClaim:
          claimName: {{ include "konstrainr-core.fullname" . }}-claim
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "konstrainr-core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: KSR_SERVICE_NAME
            value: {{ include "konstrainr-core.fullname" . }}
          - name: KSR_NAMESPACE
            value: {{ .Release.Namespace }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ include "konstrainr-core.fullname" . }}-storage
              mountPath: /app/home
          livenessProbe:
            httpGet:
              path: /echo
              port: http
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /echo
              port: http
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
