apiVersion: v1
kind: Service
metadata:
  name: {{ include "konstrainr-core.fullname" . }}
  {{ include "konstrainr-core.namespace" . | nindent 2}}
  labels:
    {{- include "konstrainr-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "konstrainr-core.selectorLabels" . | nindent 4 }}
