apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: konstrainer
  labels:
    app: konstrainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: konstrainer
subjects:
- kind: ServiceAccount
  name: konstrainer
  namespace: konstrainer
